const nationalityToCode = {
  "Spain": "ES",
  "England": "GB",
  "Germany": "DE",
  "France": "FR",
  "Italy": "IT",
  "Brazil": "BR",
  "Argentina": "AR",
  "Netherlands": "NL",
  "Portugal": "PT",
  "Belgium": "BE",
  "Uruguay": "UY",
  "Colombia": "CO",
  "Mexico": "MX",
  "USA": "US",
  "Croatia": "HR",
  "Sweden": "SE",
  "Denmark": "DK",
  "Switzerland": "CH",
  "Turkey": "TR",
  "Ukraine": "UA",
  "Egypt": "EG",
  "Morocco": "MA",
  "Tunisia": "TN",
  "Algeria": "DZ",
  "Nigeria": "NG",
  "Ghana": "GH",
  "Norway": "NO",
  "Austria": "AT",
  "Poland": "PL",
  "Romania": "RO",
  "Hungary": "HU",
  "Bulgaria": "BG",
  "Greece": "GR",
  "Israel": "IL",
  "Japan": "JP",
  "South Korea": "KR",
  "Slovakia": "SK",
  "Slovenia": "SI",
  "Venezuela": "VE",
  "Australia": "AU",
  "Cameroon": "CM",
  "Canada": "CA",
  "Chile": "CL",
  "China": "CN",
  "Czech Republic": "CZ",
  "Iran": "IR",
  "Ivory Coast": "CI",
  "Paraguay": "PY",
  "Peru": "PE",
  "Russia": "RU",
  "Scotland": "GB-SCT",
  "Senegal": "SN",
  "Serbia": "RS",
  "South Africa": "ZA",
  "Wales": "GB-WLS"
};

export default nationalityToCode;
